

CREATE TABLE [FS].[CS_CC_CONFIGURACION_PENALIZACION](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DesdeDias] [int] NOT NULL,
	[HastaDias] [int] NOT NULL,
	[PorcentajePago] [decimal](5, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

---------------

ALTER TABLE fs.clasificacion
ADD PorcentajeContado DECIMAL(5,2) NULL,
    PorcentajeCredito DECIMAL(5,2) NULL,
    PorcentajeCredito1Dia DECIMAL(5,2) NULL;

--------------

CREATE TABLE FS.CS_CC_CONFIGURACION_TOLERANCIA (
Id INT IDENTITY PRIMARY KEY,
ToleranciaPorcentaje DECIMAL(5,2) NOT NULL
);

INSERT INTO FS.CS_CC_CONFIGURACION_TOLERANCIA (ToleranciaPorcentaje)
VALUES (5.00);




